"""
Django settings for garden_timekeeper project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Debug is controlled from the .env file
DEBUG = os.getenv("DEBUG", "False") == "True"

# Local hosts permitted
ALLOWED_HOSTS = [
    ".herokuapp.com",
    "localhost",
    "127.0.0.1",
    "garden-timekeeper-588fc83d2eb9.herokuapp.com"
]


# Application definition

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third‑party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'django_summernote',
    'cloudinary',
    'cloudinary_storage',

    # Local apps
    'core',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Whitenoise for static file handling
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'garden_timekeeper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'garden_timekeeper.wsgi.application'


# Database
# If DATABASE_URL exists, us it. Otherwise fll back to SQLLite
# (Uses SQLite for development and testing (when there is no URL))
if dj_database_url:
    DATABASES = {
        'default': dj_database_url.parse(
            os.getenv("DATABASE_URL", "sqlite:///db.sqlite3"),
            conn_max_age=0,
            conn_health_checks=True,
            ssl_require=False
        )
    }
else:
    # Fallback for test environment
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Where Django collects all static files when collectstatic is run.
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Whitenoise settings
if DEBUG:
    STATICFILES_STORAGE = (
        'django.contrib.staticfiles.storage.StaticFilesStorage'
    )
else:
    STATICFILES_STORAGE = (
        'whitenoise.storage.CompressedManifestStaticFilesStorage'
    )

# -----------------------------------------------------
# Media Storage
# -----------------------------------------------------

if DEBUG:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"
else:
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_URL = "/media/"


# Crispy Forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Fallback redirect (should be taken from the accounts\login_view)
# used ifI switch to Django’s built‑in LoginView
LOGIN_REDIRECT_URL = "home"

# Force user to login again after browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.getenv(
    "SESSION_EXPIRE_AT_BROWSER_CLOSE", "True"
    ) == "True"

# Required for Django 5.x to silence warnings about primary key
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SUMMERNOTE_CONFIG = {
    # Use the in-place editor
    # (disable iframe so I can use standard CSS styling)
    'iframe': False,

    # Store Summernote uploads (images, files) in Cloudinary
    "attachment_storage": "cloudinary_storage.storage.MediaCloudinaryStorage",

    # Optional: folder prefix in Cloudinary
    "attachment_upload_to": "summernote",

    # Set the toolbar layout to be restricted so it takes less room
    #     ['style', ['bold', 'italic', 'underline', 'clear']],
    #     ['para', ['ul', 'ol', 'paragraph']],
    #     ['insert', ['link', 'picture']],
    #     ['view', ['fullscreen']],
    # ],
    'toolbar': [
        ['style', ['style']],  # includes headings
        ['para', ['ul', 'ol', 'paragraph']],
        ['insert', ['link', 'picture']],
        ['view', ['fullscreen']],
    ],

    # Optional: restrict allowed tags for safety
    'allowed_tags': [
        'p', 'br', 'strong', 'em', 'u', 'ul', 'ol', 'li', 'a',
    ],

    # Optional: restrict attributes
    'allowed_attributes': {
        'a': ['href', 'target', 'title'],
    },

    # Editor size
    'summernote': {
        'width': '100%',
        'height': '200px',
    },
}

# Allow usernames to be case insensitive
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.CaseInsensitiveUsernameBackend',
]

# prints password reset emails to the terminal for debugging.
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Email settings (production uses SendGrid via environment variables)
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")


# Restricted logging output:
# It does not expose sensitive information to users.
# It only sends errors to Heroku logs — exactly what you want.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "ERROR",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": True,
        },
    },
}

# Security settings for production
if not DEBUG:
    # Set to false to allow local Dev Instance to run in http
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    X_FRAME_OPTIONS = "DENY"
