# Generated by Django 6.0.2 on 2026-02-10 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gardenbed_unique_bed_name_per_user_case_insensitive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(blank=True, max_length=100)),
                ('lifespan', models.CharField(choices=[('ANN', 'Annual'), ('PER', 'Perennial'), ('BIE', 'Biennial')], default='PER')),
                ('type', models.CharField(choices=[('VEG', 'Vegetable'), ('FRU', 'Fruit'), ('HER', 'Herb'), ('FLO', 'Flower'), ('SHR', 'Shrub'), ('TRE', 'Tree')])),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
