# Generated by Django 6.0.2 on 2026-02-10 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.gardenbed'),
            preserve_default=False,
        ),
    ]
