# Generated by Django 6.0.2 on 2026-02-11 17:03

import django.db.models.deletion
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plant_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('all_year', models.BooleanField(default=True, help_text='If selected, this task is active all year')),
                ('seasonal_start_month', models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1, help_text='Start month')),
                ('seasonal_end_month', models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=12, help_text='End month')),
                ('frequency', models.CharField(choices=[('7d', 'Every 7 days'), ('14d', 'Every 14 days'), ('1m', 'Monthly'), ('3m', 'Quarterly'), ('6m', 'Half-yearly'), ('12m', 'Yearly')], default='7d', max_length=3)),
                ('repeat', models.BooleanField(default=True, help_text='Uncheck for a one-off task.')),
                ('notes', django_summernote.fields.SummernoteTextField(blank=True)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.plant')),
            ],
            options={
                'ordering': ['next_due', 'last_done', 'name'],
            },
        ),
    ]
