# Generated by Django 5.2.11 on 2026-02-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_planttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttask',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
