# Generated by Django 6.0.2 on 2026-02-17 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='core.gardenbed'),
        ),
    ]
