# Generated by Django 6.0.2 on 2026-02-26 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_plant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planttask',
            name='frequency',
            field=models.CharField(choices=[('7d', 'Every 7 days'), ('14d', 'Every 14 days'), ('1m', 'Monthly'), ('3m', 'Quarterly'), ('6m', 'Half-yearly'), ('12m', 'Yearly')], default='12m', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='gardenbed',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='bed_name_not_blank'),
        ),
    ]
