# Generated by Django 6.0.2 on 2026-02-26 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_plant_plant_name_not_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planttask',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='task_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='planttask',
            constraint=models.CheckConstraint(condition=models.Q(('frequency', ''), _negated=True), name='task_frequency_not_blank'),
        ),
    ]
